version: '3.7'
services: 
  jaeger:
    container_name: jaeger
    image:  jaegertracing/all-in-one:1.6
    environment: 
    - TZ=Asia/Taipei 
    ports:
      - 6831:6831/udp
      - 16686:16686
      - 14268:14268
  hotrod:
    container_name: hotrod
    image:  jaegertracing/example-hotrod:1.6
    environment: 
    - TZ=Asia/Taipei 
    - jaeger-agent.host-port=jaeger:6831
    ports:
      - 8080-8083:8080-8083
    command: all --jaeger-agent.host-port=jaeger:6831
    depends_on:
      - jaeger