version: '2'
services:
  mysqldb:
    container_name: mysql
    image: mysql/mysql-server:5.6.44
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/data/mysql:/var/lib/mysql
    - $PWD/my55.cnf:/etc/my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=mysqlpwd
    - MYSQL_DATABASE=chapter04
    - MYSQL_USER=chapter04
    - MYSQL_PASSWORD=mysqlpwd
    - EXTRA_OPTS="--lower_case_table_names=1"
    - TZ=Asia/Taipei
    network_mode:  "host"
    # ports: 
    #  - "3306:3306" 